//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityProjesi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DbEntityProductEntities : DbContext
    {
        public DbEntityProductEntities()
            : base("name=DbEntityProductEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBLCATEGORİES> TBLCATEGORİES { get; set; }
        public virtual DbSet<TBLCUSTOMER> TBLCUSTOMER { get; set; }
        public virtual DbSet<TBLPRODUCT> TBLPRODUCT { get; set; }
        public virtual DbSet<TBLSALES> TBLSALES { get; set; }
        public virtual DbSet<TBLADMİN> TBLADMİN { get; set; }
    
        public virtual ObjectResult<BRANDGETIR_Result> BRANDGETIR()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BRANDGETIR_Result>("BRANDGETIR");
        }
    }
}
