//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityProjesi
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLSALES
    {
        public int SALESID { get; set; }
        public Nullable<int> PRODUCT { get; set; }
        public Nullable<int> CUSTOMER { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
    
        public virtual TBLCUSTOMER TBLCUSTOMER { get; set; }
        public virtual TBLPRODUCT TBLPRODUCT { get; set; }
    }
}
